### ISSUE TITLE
Fails on Docker swarm

### ISSUE THREAD

**Issue by Torhamilton** [c0sogi/LLMChat#32]
["WARNING You Probably Don't Need this Docker Image:](https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker) " we should follow that advice and remove Gunicorn and the requirement for forwarded-ip. You can't used fixed ip for traefik in swarm mode or Kubernetes.  Also better to let swarm manage replication instead of Gunicorn workers

**Comment by c0sogi** [comment]
If you use Traefik to route to an API container without a forwarded ip, the IP of the accessor will not be logged. Is this okay?

**Comment by c0sogi** [comment]
I'm not familiar with Kubernetes and Docker swarms, but doesn't Traefik need to pre-set a trusted IP in order to reference the `X-Forwarded-For` header? It seems like this would be necessary to prevent spoofing when routing through multiple proxies and the accessor's original IP is passed in the header.

**Comment by Torhamilton** [comment]
Traefik has this covered for swarm, compose or k8s. All internal traefik can be trusted. We use [forwardedHeaders.trustedIPs](https://doc.traefik.io/traefik/v2.2/routing/entrypoints/#forwarded-headers)

Since Traefik is the edge router within the Docker Compose network, and it's the first point of contact for incoming requests, you can trust all IPs within the Docker Compose network (because they are all internal to the network and under your control). This means that you could potentially specify the entire subnet of the Docker Compose network as trusted in the Traefik configuration.

However, note that the X-Forwarded-* and Forwarded headers are typically used in situations where there are multiple hops between the client and the server (for example, client -> load balancer -> proxy -> server), so if Traefik is the only hop between the client and the server, you might not need to use these headers at all.

**Comment by c0sogi** [comment]
Do we really need to remove Gunicorn? There may be cases where we deploy without using Kubernetes, and since Gunicorn is responsible for distributing the workers, it seems unlikely that using Kubernetes will cause any problems.

**Comment by Torhamilton** [comment]
I believe compose supports replication too. Also I noticed Gunicorn makes the image very large. However we can leave it for now.

**Comment by c0sogi** [comment]
I didn't remove Gunicorn, but I did remove the static IP dependency for production compose in the new commit. Please leave a comment if you have anything to add.

**Comment by Torhamilton** [comment]
I get gateway timeout, error 504. It worked only twice but fails on docker-compose down/up. We need to guarantee connection will always be accepted.

**Comment by c0sogi** [comment]
This is caused by Traefik not catching the reverse proxy because we added a private network. it appears that the problem is only with prod compose. First, please add `"traefik.docker.network=reverse-proxy-public"` to the labels of your api.
For example, you can define it as follows. I'll fix it in the next commit.
```yaml
  api:
    image: cosogi/llmchat:230610
    restart: always
    env_file:
      - .env
    command:
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy-public"
      - "traefik.http.routers.api.rule=HostRegexp(`${HOST_MAIN}`, `{subdomain:[a-z]+}.${HOST_MAIN}`, `${HOST_IP}`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.services.api.loadbalancer.server.scheme=http"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.routers.api.tls.domains[0].main=${HOST_MAIN}"
      - "traefik.http.routers.api.tls.domains[0].sans=${HOST_SUB}"
    depends_on:
      - proxy
      - db
      - cache
      - vectorstore
    volumes:
      - .:/app
    networks:
      - api-private
      - reverse-proxy-public
```
